services:
  temurin:
    image: eclipse-temurin:17-jdk
    container_name: temurin-container
    volumes:
      - ./build/libs:/app
    working_dir: /app
    command: ["java", "-jar", "cubic-server.jar"]
    ports:
      - "8080:8080"

  minio:
    image: minio/minio
    container_name: minio-container
    environment:
      MINIO_ROOT_USER: "adminuser"
      MINIO_ROOT_PASSWORD: "strongpassword"
    volumes:
      - ./minio-data:/data
    ports:
      - "9005:9000"
    command: server /data
    profiles: ["dev"]


  postgresql:
    image: postgres:15-alpine
    container_name: postgresql-container
    environment:
      POSTGRES_DB: blocdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # PostgreSQL은 기본적으로 5432 포트를 사용
    profiles: ["dev"]

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    profiles: ["dep", "dev"]

  grafana:
    image: grafana/grafana
    ports:
      - "3333:3000"
    depends_on:
      - prometheus
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning