version: '3.8'

services:
  temurin:
    image: eclipse-temurin:17-jdk
    container_name: temurin-container
    volumes:
      - ./app:/usr/src/app
    working_dir: /usr/src/app
    command: ["java", "-jar", "your-app.jar"] # 여기서 your-app.jar을 실행할 자바 애플리케이션으로 변경하세요
    ports:
      - "8080:8080" # 필요에 맞게 포트를 설정하세요
    profiles: ["dep"] # 프로파일을 설정하세요

  minio:
    image: minio/minio
    container_name: minio-container
    environment:
      MINIO_ROOT_USER: "adminuser" # 기본 관리자 사용자 이름
      MINIO_ROOT_PASSWORD: "strongpassword" # 기본 관리자 비밀번호
    volumes:
      - ./minio-data:/data # 데이터를 저장할 로컬 디렉토리와 마운트
    ports:
      - "9005:9000" # MinIO는 기본적으로 9000 포트를 사용
    command: server /data
    profiles: ["dep", "dev"]


  postgresql:
    image: postgres:15-alpine
    container_name: postgresql-container
    environment:
      POSTGRES_DB: blocdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # PostgreSQL은 기본적으로 5432 포트를 사용
    profiles: [ "dep", "dev" ]

