server:
  port: 8085

spring:
  application:
    name: block-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  config:
    import: optional:file:.env[.properties]
  jpa:
    database: postgresql
