server:
  port: 8085

spring:
  application:
    name: block-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    database: postgresql
  servlet:
    multipart:
      max-file-size: 10GB  # 최대 파일 크기
      max-request-size: 10GB  # 최대 요청 크기