server:
  port: 8085

spring:
  application:
    name: block-backend2
  datasource:
    url: jdbc:postgresql://localhost:5432/blocdb
    username: root
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create # 개발 중에는 'update', 운영 환경에서는 'none' 또는 'validate'로 설정
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight: true
        use_sql_comments: true
  minio:
    endpoint: http://localhost:9005
    access-key: adminuser
    secret-key: strongpassword
    bucket: bloc # 사용하려는 버킷 이름


logging:
  level:
    org:
      springframework:
        web: DEBUG # 로그 레벨 설정, 필요에 따라 변경 가능

